app1/app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
     path('user/', include('users.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += [
    path("__debug__/", include("debug_toolbar.urls")),  
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/goods/urls.py
from django.urls import include, path

from goods import views

app_name='goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),    
]

app1/main/urls.py
from django.urls import path

from main import views

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    
]

app1/users/urls.py
from django.urls import path

from users import views

app_name='users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.cabinet, name='cabinet'), 
    path('announcement/', views.profile, name='profile'), 
    path('logout/', views.logout, name='logout'),    
]

app1/templates/base.html
{% load static %}
{% load goods_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/photo.jpg" %}">
    <title>{{ title }}</title>
    <!-- Ваша таблиця стилів (CSS) або інші метадані -->
    <link rel="stylesheet" href="{% static "deps/css/styles_form.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/style.css" %}">
	<link rel="stylesheet" href="{% static "deps/css/styles_apartments.css"%}">
    <link rel="stylesheet" href="{% static "deps/css/gallery.css"%}">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url "main:index" %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url "user:login" %}">Увійти/Зареєструватися</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Мій профіль
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-white" href="{% url "user:cabinet" %}">Профіль</a>
                                    </li>
                                    <li><a class="dropdown-item  text-white" href="{% url "user:profile" %}">Додати оголошення</a>
                                    </li>
                                    {% if user.is_admin or user.is_staff %}
                                        <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Адмін панель</a></li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item  text-white" href="{% url "user:logout" %}">Вийти</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <div class="dropdown mb-2" style="margin: 0 auto;">
                        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                            aria-expanded="false">
                            Каталог
                            <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                                height="16">
                        </button>
                        <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                            {% tag_categories as categories %}
                            {% for category in categories %}
                                <li><a class="dropdown-item text-white" href="{% url "catalog:index" category.slug %}">{{category.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <form class="d-flex" role="search" action="{% url "catalog:search" %}" method="get">
                        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Пошук</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    {% include "includes/notifications.html" %}
    <main> 
        
        {% block content %}
        {% endblock%}

    </main>
    
    {% block footer %}
    {% endblock %} 

    <!-- Ваші скрипти чи інші ресурси -->
    <script src="{% static "deps/js/script_form.js" %}"></script>
    <script src="{% static "deps/js/gallery.js"%}"></script>
    <script src="{% static "deps/js/script.js"%}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/jquery-events.js" %}"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>